apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
#resources:
#  - namespace.yaml
#  - repository.yaml
#  - release.yaml
configMapGenerator:
  - name: vscode-values
    files:
      - coder.yaml
  - name: db-values
    files:
      - postgresql.yaml
secretGenerator:
  - name: coder-db-url
    literals:
      - url="postgres://coder:coder@coder-db-postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable"
configurations:
  - kustomizeconfig.yaml