apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mon-site
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./mon-site
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: mon-site
  targetNamespace: test
  timeout: 3m0s
  wait: true

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mon-site
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/FredPi17/fredericpinaud

---