
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vscode
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./vscode
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: mon-site
  targetNamespace: default
  timeout: 3m0s
  wait: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vscode
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.coder.com/v2

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 1m
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
--- 

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vscode
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: coder
      version: '2.22.1'
      sourceRef:
        kind: HelmRepository
        name: vscode
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 1
  valuesFrom:
    - kind: ConfigMap
      name: vscode-values-c7dbf996d9

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder-db
  namespace: default
spec:
  interval: 10m
  releaseName: coder-db
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: postgresql
        
  chartRef:
    kind: OCIRepository
    name: postgresql
  valuesFrom:
    - kind: ConfigMap
      name: postgresql-values-m7cd6f62bb