
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vscode
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./vscode
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: HelmRelease
    name: vscode
  targetNamespace: default
  timeout: 3m0s
  wait: true
---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vscode
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm.coder.com/v2

--- 
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vscode
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: vscode
      version: '2.22.1'
      sourceRef:
        kind: HelmRepository
        name: vscode
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 1
  valuesFrom:
    - kind: ConfigMap
      name: vscode-values

